### ISSUE TITLE
Objetivos para cerrar el Milestone 0

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#56]
- [x] Repositorio creado 
- [x] Especificación del problema a solucionar. #2 
- [x] Establecer los objetivos del proyecto. #3 
- [x] Estudiar estado del arte. #4 , #39 y #41. Además del PR #34 
- [x] Conocer los usuarios que tienen el problema a solucionar (Usuarios, User Journey e HU). #5 , #6 y #7 
- [x] Fijar los milestone. #8 y #43. Además del PR #31 
- [x] Tener funcionando un sistema de comprobación ortográfica continua. #17 
- [x] Tener la documentación disponible siempre en formato PDF y en su última versión. #18 
- [ ] Añadir Spotify al estado del arte (ha sido presentado después de desarrollar el estado del arte). #46
