### ISSUE TITLE
Objetivos para cerrar el Milestone 1

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#57]
- [x] Elegir el lenguaje de programación para el dispositivo móvil. #49 
- [x] Elegir el lenguaje de programación para el dispositivo receptor. Módulo NFC. #47 
- [x] Elegir el lenguaje de programación para el dispositivo receptor. Módulo streaming. #55 
- [x] Elegir test runner y biblioteca de aserciones para los test unitarios. #50 
- [x] Definir clases "port" y "adapter"
