### ISSUE TITLE
Objetivos para cerrar el Milestone 2

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#63]
- [x] Capturar el audio interno. #52 
- [x] Guardar ese audio capturado en un archivo reproducible. #66 
- [x] Verificar el archivo de audio capturado. #52 
- [x] Documentar el proceso y las elecciones. #52 
- [x] Estructurar y modularizar el código correctamente.
- [ ] Escribir test.
