### ISSUE TITLE
Objetivos para cerrar el Milestone 3

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#67]
- [x] Instalar SO a la Raspberry.
- [x] Instalar drivers PN532 en la Raspberry.
- [x] Conectar satisfactoriamente PN532 a la Raspberry.
- [x] Instalar los lenguajes de programación y bibliotecas necesarias en la Raspberry.
- [x] Documentar el proceso.
