### ISSUE TITLE
Objetivos para cerrar el Milestone 4

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#72]
- [x] Enviar el audio interno capturado en el milestone 2 hacia el dispositivo receptor. #53 
- [x] Recibir el audio interno y reproducirlo en el dispositivo receptor. #54 
- [x] Comunicar la IP del dispositivo receptor. #70 y #71 
- [x] Documentar el proceso.
- [ ] Escribir test.
