### ISSUE TITLE
Objetivos para cerrar Milestone 5 

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#77]
- [x] Añadir costes de proyecto y de productización.
- [x] Añadir conclusiones.
- [x] Añadir trabajos futuros.
- [x] Repasar explicaciones sobre issues, milestone y demás metodología utilizada.
- [x] Repasar explicaciones sobre protocolos, tecnologías y especificaciones.
